### PR TITLE
use exit code 1 instead of 128

### PR DESCRIPTION
**Pull request by ungoldman**
Hi @Kikobeats!

This is a handy module. Thanks for making it!

I think the error code you're using is invalid. The `128` error code is reserved for `Invalid argument to exit`. Please see http://tldp.org/LDP/abs/html/exitcodes.html for reference. I changed it to `1` in my fork.

### CODE REVIEW

**Comment by Kikobeats** [comment]
Interesting, I catch the idea from here:

https://github.com/sindresorhus/np/blob/master/np.sh

Also affect to my git-garbage repository:

https://github.com/Kikobeats/git-garbage/blob/master/garbage.sh

Do you think that is the right way change 128 → 1 ?

**Comment by Kikobeats** [comment]
@ngoldman say me something :)

**Comment by ungoldman** [comment]
I don't know, the documentation I read the other day (which I linked to above) seemed to indicate that 128 was reserved for "invalid exit code", but I see people using 128 in other places as well. If you want to keep it the same as the source you got if from (@sindresorhus's np module) then you should probably close this PR.

**Comment by Kikobeats** [comment]
I'm going to ship this in `v1.0.2` 👍

**Pull request merged**
